### ISSUE TITLE
Segfault in ld on ARM

### ISSUE THREAD

**Issue by Hendi48** [kubo/injector#14]
I have a Linux 3.10.79 embedded system with glibc-2.18 running on an armv7l processor. When I use the injector on any process, the process crashes with a segfault.

Running the target process with `LD_DEBUG=all` only yields:
```
  7198:     file=/path/to/my/lib.so [0];  dynamically loaded by /lib/libc.so.6 [0]
  7198:     file=/path/to/my/lib.so [0];  generating link map
```

The fault address is [this line](https://github.com/bminor/glibc/blob/release/2.18/master/elf/dl-load.c#L1503) in `_dl_map_object_from_fd`, more specifically in the `STR` instruction for the statement. At the time of crash, the stack pointer points to like -0x800 bytes to the top of the stack that was `mmap`ed by the injector, so that seems alright at least.

The variable it tries to store to is in this mapped area:
```
b6f15000-b6f16000 r-xp 0001e000 fe:01 281        /lib/ld-2.18.so
```
Does `/proc/pid/maps` accurately reflect the access rights at runtime (even if they were changed after the initial mapping)? Then it would explain the segfault since it's not writable. It seems to be the `.data.rel.ro` segment. A test program I compiled can call `dlopen` on the same library just fine though, so it doesn't seem to be a general issue with the system.

**Comment by Hendi48** [comment]
It works when I change the `dlopen_addr` call to `RTLD_LAZY | __RTLD_DLOPEN`. It needs that internal glibc flag in order to take the code path that changes memory protections.

**Comment by kubo** [comment]
@Hendi48 
Thanks! I fixed it as you suggested.
