### ISSUE TITLE
PTRACE_ATTACH error : Operation not permitted

### ISSUE THREAD

**Issue by SlimSnow** [kubo/injector#16]
env:
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

x86_64

cc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**Comment by SlimSnow** [comment]
![image](https://user-images.githubusercontent.com/46469516/163987839-6d027bfe-f4ed-4974-869f-186eec338043.png)

![image](https://user-images.githubusercontent.com/46469516/163987888-fd3701cc-2322-48b5-9571-ec179ccab6c6.png)

**Comment by SlimSnow** [comment]
On Linux via command line

**Comment by SlimSnow** [comment]
ptrace errno 1

**Comment by kubo** [comment]
@SlimSnow 
See https://github.com/gaffe23/linux-inject#caveat-about-ptrace.
You may need to change your OS's setting. Otherwise run injector with root privilege.

If you run it on ubuntu in docker, see https://stackoverflow.com/questions/42029834/gdb-in-docker-container-returns-ptrace-operation-not-permitted.

**Comment by SlimSnow** [comment]
@kubo  Thank you very much.
but a new issuse is here:
dlopen failed
![image](https://user-images.githubusercontent.com/46469516/164122843-ed1d1ee4-686e-46f0-b41c-86561ca04d67.png)
![image](https://user-images.githubusercontent.com/46469516/164122892-237db863-a793-4815-902c-45613ed60819.png)
why my .so file can not open?Can you give me some suggestions about this?

**Comment by kubo** [comment]
There are many possible reasons for a dlopen error.
* Does the architecture of target process match that of the .so file?
* The .so file is in a directory which the target process cannot see.
* Some symbols in the .so file are not resolved.
