### ISSUE TITLE
Doesn't work on Linux via command line

### ISSUE THREAD

**Issue by vlakreeh** [kubo/injector#2]
I'm trying to inject into the provided test target with the test library and I haven't been able to do it successfully, [image here](https://zeb.website/ReceptivePreviousPoison.png). I'm fairly sure the error stems from the `injector__call_function` function in `remote_call.c` but I don't have the C knowledge to figure out a fix.

**Comment by kubo** [comment]
Could you post your environment?
* Distribution name and version (`cat /etc/os-release`)
* CPU architecture (`uname -m`)
* C compiler version (`cc --version`)

 It works on my environment: Ubuntu 16.04, x86_64, gcc 5.4.0.

**Comment by vlakreeh** [comment]
### cat /etc/os-release
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### uname -m

```
x86_64
```

### cc --version

```
cc (GCC) 9.1.0
```

**Comment by kubo** [comment]
Thanks for the information.
I reproduced the issue. I'll check it later.

**Comment by kubo** [comment]
@vlakreeh I pushed a commit. Could you try it?

**Comment by vlakreeh** [comment]
All fixed, thanks!
