### ISSUE TITLE
Support for MIPS

### ISSUE THREAD

**Issue by enty8080** [kubo/injector#23]
Hi, @kubo 

I found your tool very useful. Frankly, I have started developing a project where I want to use injector as a dependency for injecting shared libraries to a processes. So, I am just curious about if will you implement MIPS support to it? It will be great to have an ability to do injecting on embedded devices with this architecture.

Thanks,
Ivan Nikolsky (@enty8080)

**Comment by kubo** [comment]
@enty8080 
I added MIPS support.

Well, I recommend to use this just for fun. It may stop processes. See https://github.com/kubo/injector#caveats.

**Comment by enty8080** [comment]
@kubo Thanks. Your tools is great and I hope I won't face such problems, but I do not really understand this caveat. May it stop all the processes including init or just the target process? And any ways to prevent this?

**Comment by kubo** [comment]
> May it stop all the processes including init or just the target process? 

It may stop just the target process.

> And any ways to prevent this?

It is possible in theory but it is difficult for me.

The idea is:
1. attach to the target process.
2. get a backtrace of the target process as [gdb does](https://sourceware.org/gdb/current/onlinedocs/gdb/Backtrace.html).
3. if the backtrace includes memory management functions such as `malloc`, `calloc`, `strdup`, `free`, step the target process until they disappear from the backtrace.
4. Here is safe to inject a shared library.

If the target process holds a lock used by memory management functions, injector's library loading, which calls `malloc` internally, tries to hold the same lock in the same thread and stops forever.

**Comment by enty8080** [comment]
@kubo Thanks for description. Also, I have got a question. So your tool work only on little endian systems or big too? I have this question because in README there is only armel and mipsel, no mipsbe or armbe.

**Comment by kubo** [comment]
It will work also on big endian systems though I have not tested it.

I checked that it was compiled by the following compilers on ubuntu 20.04 x86_64. However I could test only three: mipsel n32 (`-mabi=n32`), mipsel o32 (`-mabi=32`) and mips64el.

* mips-linux-gnu-gcc (compiler option `-mabi=n32`)
* mips-linux-gnu-gcc (compiler option `-mabi=32`)
* mipsel-linux-gnu-gcc (compiler option `-mabi=n32`)
* mipsel-linux-gnu-gcc (compiler option `-mabi=32`)
* mips64-linux-gnuabi64-gcc
* mips64el-linux-gnuabi64-gcc
* mipsisa32r6-linux-gnu-gcc (compiler option `-mabi=n32`)
* mipsisa32r6-linux-gnu-gcc (compiler option `-mabi=32`)
* mipsisa32r6el-linux-gnu-gcc (compiler option `-mabi=n32`)
* mipsisa32r6el-linux-gnu-gcc (compiler option `-mabi=32`)
* mipsisa64r6-linux-gnuabi64-gcc
* mipsisa64r6el-linux-gnuabi64-gcc

**Comment by enty8080** [comment]
@kubo I am just curious if it will work on embedded Linux. For instance, router that has Linux 2.5 with musl and mipsel CPU. I am gonna test this, but I also want to know if you think this will work.

**Comment by kubo** [comment]
I think that it works. Support for musl libc was contributed at https://github.com/kubo/injector/pull/22.

BTW, how about [`LD_PRELOAD` or `/etc/ld.so.preload`](https://man7.org/linux/man-pages/man8/ld.so.8.html) in order to inject libraries?

As for macOS, I won't support it. I don't know how to do it on macOS and I don't have macOS machine suitable for the latest OS. (I have macbook air mid 2013.)

**Comment by enty8080** [comment]
@kubo I thought `LD_PRELOAD` can only inject shared library to the app, that you run at the same time. I thought you can't use `LD_PRELOAD` for injecting `.so` to the running process.

**Comment by kubo** [comment]
@enty8080 You are correct. It isn't in-place replacement of injector. I recommend that you have a rethink about your application design because injector have the caveat I cannot fix.
