### ISSUE TITLE
Support RISC-V

### ISSUE THREAD

**Issue by TheOiseth** [kubo/injector#24]
It would be great to add support RISC-V architecture

**Comment by kubo** [comment]
Code for RISC-V was committed. See https://github.com/kubo/injector/commit/0f18fd2d5ee1b8d2fdb1e7d44e9c88182c537d78
I have not tested it because I don't have RISC-V machines or VMs. It works unless there are pitfalls I'm unaware of.

**Comment by kubo** [comment]
I tested  it on [Ubuntu 22.04.1 riscv64 on QEMU](https://wiki.ubuntu.com/RISC-V#Booting_with_QEMU).
It passed tests after small fixes.

I closed this though I have not tested on riscv32.
