### ISSUE TITLE
Compile for Windows on Linux (mingw)

### ISSUE THREAD

**Issue by enty8080** [kubo/injector#30]
Hi @kubo ,

Can you please add rule to compile windows sources using mingw cross-compiler if it is possible.

I love this tool a lot BTW.

Regards,
Ivan Nikolsky (@enty8080)

**Comment by kubo** [comment]
Closed by https://github.com/kubo/injector/commit/caecaed0405ecc87150fc91b1eab19d115650039

See https://github.com/kubo/injector#windows-mingw-w64
