### ISSUE TITLE
failed to open /run/host/usr/lib/x86_64-linux-gnu/libc.so.6. 

### ISSUE THREAD

**Issue by xsip** [kubo/injector#38]
Hi !
When i try running the injector on ubuntu i get the following error. 
Could you explain me whats going on here?
Thx in advance!
failed to open /run/host/usr/lib/x86_64-linux-gnu/libc.so.6. (dev:0x811, ino:9439334)

**Comment by kubo** [comment]
@xsip @Run1e 
Could you post more information? What kind of process?

General processes uses `/usr/lib/x86_64-linux-gnu/libc.so.6`, not `/run/host//usr/lib/x86_64-linux-gnu/libc.so.6`.

Could you post the output of the following commands. (replace `<PID_OF_TARGET_PROCESS>` with actual process id.)

```shell
grep libc.so.6 /proc/<PID_OF_TARGET_PROCESS>/maps
ls -li /usr/lib/x86_64-linux-gnu/libc.so.6
ls -li /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
ls -li /proc/<PID_OF_TARGET_PROCESS>/root/usr/lib/x86_64-linux-gnu/libc.so.6
ls -li /proc/<PID_OF_TARGET_PROCESS>/root/run/host/usr/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by Run1e** [comment]
Hi there @kubo,

I deleted my comment as I realized that my issue was most likely container related. As such this info doesn't belong here but I'll type it out anyway.

I am trying to inject a shared object into an instance of Counter-Strike 2 (for movie-making purposes and not nefarious ones, believe it or not), which runs under the Steam Linux Runtime (version 3, sniper). Judging from his repos I would assume @xsip is trying to do the same, though probably not for innocent reasons.

The steamrt uses containers to create consistent environments for Linux games, so I'm trying to inject an object into a process running in another namespace (with a different fs), which probably causes the error somehow. Actively experimenting with stuff but I'm not familiar with working with containers at such a low level.

Here you go:
```bash
+ grep libc.so.6 /proc/115714/maps
7f3307c13000-7f3307c39000 r--p 00000000 fe:00 5767187                    /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
7f3307c39000-7f3307d8e000 r-xp 00026000 fe:00 5767187                    /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
7f3307d8e000-7f3307de1000 r--p 0017b000 fe:00 5767187                    /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
7f3307de1000-7f3307de5000 r--p 001ce000 fe:00 5767187                    /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
7f3307de5000-7f3307de7000 rw-p 001d2000 fe:00 5767187                    /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
+ ls -li /usr/lib/x86_64-linux-gnu/libc.so.6
5767187 -rwxr-xr-x 1 root root 1922136 Jan 23 21:57 /usr/lib/x86_64-linux-gnu/libc.so.6
+ ls -li /run/host/usr/lib/x86_64-linux-gnu/libc.so.6
ls: cannot access '/run/host/usr/lib/x86_64-linux-gnu/libc.so.6': No such file or directory
+ ls -li /proc/115714/root/usr/lib/x86_64-linux-gnu/libc.so.6
ls: cannot access '/proc/115714/root/usr/lib/x86_64-linux-gnu/libc.so.6': No such file or directory
+ ls -li /proc/115714/root/run/host/usr/lib/x86_64-linux-gnu/libc.so.6
5767187 -rwxr-xr-x 1 root root 1922136 Jan 23 21:57 /proc/115714/root/run/host/usr/lib/x86_64-linux-gnu/libc.so.6
```

**Comment by kubo** [comment]
Thanks. Could you try the latest code?

I committed https://github.com/kubo/injector/commit/c719b4f6b3bde75fd18d4d0c6b752a68dce593aa#diff-857597e3f024ad94f222e5b1b847eecce126198be58b1158867f58a25fe0a76bR358 for Flatpak applications to close (https://github.com/kubo/injector/pull/36). It fixes your issue also.

**Comment by kubo** [comment]
@xsip 
I close this. The latest code will resolve your issue also. If it doesn't, let's me know.
