### ISSUE TITLE
Attach xxxx failed. WriteProcessMemory error: Invalid access to memory location.

### ISSUE THREAD

**Issue by huhuang03** [kubo/injector#4]
Same code, not work on a vm machine which is  win10 2016 Enterprise Edition . Any possible reason I should check?

**Comment by kubo** [comment]
@huhuang03 Could you try [this branch](https://github.com/kubo/injector/tree/travis)? It includes https://github.com/kubo/injector/commit/c78829c8d11ea0da3a9b208587d652a1bbd6689a.

**Comment by huhuang03** [comment]
Yes, the [travis](https://github.com/kubo/injector/tree/travis) branch works.
