### ISSUE TITLE
Inconsistency detected by ld.so

### ISSUE THREAD

**Issue by Marcin-Szmagara** [kubo/injector#5]
Once in about 30 injections (seems random, hard to reproduce) the target process will pause and the shared object will not get injected. Any signal send to target will resume it and injector will print `The target process unexpectedly stopped by signal <signum>.`

Another try will result in crash of the target with error `Inconsistency detected by ld.so: dl-open.c: 272: dl_open_worker: Assertion _dl_debug_initialize (0, args->nsid)->r_state == RT_CONSISTENT' failed!`.

I inject the same `.so`, but with different names to the same process.

My system:
```
Ubuntu 18.04.5 LTS
x86_64
gcc 7.5.0
```

**Comment by kubo** [comment]
Does the target process allocate and free memory frequently? If so, it may pause by the following known issue:

In https://github.com/kubo/injector#caveats
> `__libc_dlopen_mode` internally calls `malloc()` and `free()`. If the target process is allocating or freeing memory and `malloc()` or `free()` holds a lock, this may stop the process forever.

**Comment by Marcin-Szmagara** [comment]
It does allocate and free memory frequently. This is likely the problem, but is this really hard to solve?

Assuming the process calls those functions frequently enough, we could hook both of them and wait until either gets called to proceed with injection? That would of course be another mode, since we can't assume that in general.

Closing, as this already is in the caveats, but would like to hear your opinion on the above idea.
